### ISSUE TITLE
Link to tutorial example source code broken?

### ISSUE THREAD

**Issue by mibieri** [hplgit/fenics-tutorial#16]
I'm currently working with your Fenics tutorial. [`Here`](http://hplgit.github.io/fenics-tutorial/doc/web/index.html) one can choose between PDF and HTML, plus there's also a linkt to the tutorial examples. The link to the tutorial examples seems to be broken.

**Comment by alogg** [comment]
Thanks. This will be fixed when we publish the final version which will appear at a new URL: http://www.fenicsproject.org/tutorial/

**Comment by mibieri** [comment]
So that's not the final version so far? Wouldn't it be possible to publish
a preliminary version of the examples? That would be very helpful.
Currently, it's very difficult to find a consistent set of
examples+tutorial. There are examples in the Docker image, but they do not
really match the ones in the tutorial.

**Comment by alogg** [comment]
I have two referee reports on my desk with detailed comments that will be
fixed before the book is printed. The plan is to have the final version
ready by the end of next week.

You can find all the example programs here:

https://github.com/hplgit/fenics-tutorial/tree/master/src/vol1/python

--
Anders


ons 19 okt. 2016 kl 11:22 skrev mibieri <notifications@github.com>:

**Comment by alogg** [comment]
Links to the example programs have been added to the soon-to-be-published tutorial web page:

https://fenicsproject.org/new/tutorial/
