### ISSUE TITLE
Simplification of magneto statics equation (4.20)

### ISSUE THREAD

**Issue by joha2** [hplgit/fenics-tutorial#19]
In the magneto statics section I did not really understand how you came from the rot rot equation to the grad div-type one (before restricting to two dimensions, eq. (4.20)): For a homogenious medium with mu = const this step is trivial by using the Coulomb gauge, but I think this is not valid here anymore. Could you please explain this step further and add more details?

**Comment by alogg** [comment]
Good point, will fix.

**Comment by joha2** [comment]
To improve my unspecific comment from above I worked (4.20) out in more detail:

![equation](http://latex.codecogs.com/gif.latex?J_i%3D%5Cvarepsilon_%7Bijk%7D%5Cpartial_j%28%5Cmu%5E%7B-1%7D%5Cvarepsilon_%7Bkpm%7D%5Cpartial_pA_m%29%5C%5C%3D%5Cvarepsilon_%7Bijk%7D%5Cvarepsilon_%7Bkpm%7D%5Cpartial_j%28%5Cmu%5E%7B-1%7D%5Cpartial_pA_m%29%5C%5C%3D%28%5Cdelta_%7Bip%7D%5Cdelta_%7Bjm%7D-%5Cdelta_%7Bim%7D%5Cdelta_%7Bjp%7D%29%5Cpartial_j%28%5Cmu%5E%7B-1%7D%5Cpartial_pA_m%29%5C%5C%3D%5Cpartial_m%28%5Cmu%5E%7B-1%7D%5Cpartial_iA_m%29-%5Cpartial_m%28%5Cmu%5E%7B-1%7D%5Cpartial_mA_i%29)

In the Nabla calculus used in the tutorial this would be (if I understood correctly):

![equation](http://latex.codecogs.com/gif.latex?J%3D%5Cnabla%5Ccdot%28%5Cmu%5E%7B-1%7D%28%28%5Cnabla%20A%29%5ET-%5Cnabla%20A%29%29%0D%0A)

For the upper derivation I used the index picture with Einsteinian summation convention (double indices are summed over) and the contraction relation of the epsilon symbols (which are just totally antisymmetric unit (pseudo-)tensors). In the last step the first term is the one which is usually removed by using the Coulomb gauge. The last term is the one you solved afterwards with fenics. I wonder whether there is a standard approach to gauge the first term away for inhomogenious media with non-constant mu.

(Hopefully these formula links stay stable ;-))

**Comment by alogg** [comment]
I won't have time to fix this now, but it can possibly be fixed for a new edition. Thanks for the suggestion!
