### ISSUE TITLE
Please add some references for further research for the non-standard examples

### ISSUE THREAD

**Issue by joha2** [hplgit/fenics-tutorial#20]
Besides the list of references at the beginning, could you please give some references for further research in the appropriate subsections? For a beginner in FEM methods and special treatment of physical theories in FEM, a few (beginner) references for e.g. the non-standard examples (elasticity theory, magneto statics, navier-stokes) would be very helpful.

**Comment by alogg** [comment]
Good point, will fix.

**Comment by alogg** [comment]
I won't have time to fix this now, but it can possibly be fixed for a new edition. Thanks for the suggestion!
