### ISSUE TITLE
Some candidates for formulas with footnotes clarifying vector/tensor structure by using index picture

### ISSUE THREAD

**Issue by joha2** [hplgit/fenics-tutorial#21]
In my tutorial (version Nov 9, 2016) I identified the following formulas:
Mostly these contain tensor structure or (from my point of view) a more or less missleading 
contraction of more than one Nabla.

Some introductory formulas from the linear elasticity problem:

* (3.20), (3.21), (3.22)
* (3.23)
* Second formula in 3.3.2 Variational formulation, the integration by parts with the full contraction

The Navier-Stokes equations:

* (3.29), (3.30)

Some of the formulas in the discussion about the outflow boundary conditions for Navier-Stokes.

* pn-mu (nabla u) n
* pn-mu (nabla u)^T n

Derived from the Maxwell equations:

* (4.20)

In this context the discussion (grad(u) vs. nabla_grad(u)) could be moved to somewhere at the beginning, because it is very enlighting in order to understand the more complicated formulas of continuum mechanics and covers the index structure in more detail.

**Comment by alogg** [comment]
I won't have time to fix this now, but it can possibly be fixed for a new edition. Thanks for the suggestion!
