### ISSUE TITLE
The code in ft08

### ISSUE THREAD

**Issue by xuanyuan9288** [hplgit/fenics-tutorial#22]
In file **_ft07_navier_stokes_channel.py_**, when we define expressions used in variational forms, the rho is defined as _rho = Constant(rho)_.
But in the file _**ft08_navier_stokes_cylinder.py**_, the sentence is missing.
Should I add the sentence in the file **_ft08_**?

**Comment by alogg** [comment]
Well spotted. Yes please add and make a pull request.

**Comment by alogg** [comment]
This has been fixed now.
