### ISSUE TITLE
Mistakes on page 84 and page 85

### ISSUE THREAD

**Issue by xuanyuan9288** [hplgit/fenics-tutorial#23]
On page 84, it reads 
_g(x, y) = 4, y = 1._
However, as the definition of _g_, it should equal to _-4_ on _y = 1_.
So the extension is
_g(x, y) = -4y._

On page 85, we need to include the Neumann condition as
_g = Expression('-4*x[1]', degree = 1)_

By the way, the Dirichlet boundary condition also can be written as
_boundary = '(near(x[0], 0, 1e-14) || near(x[0], 1, 1e-14)) && on_boundary'._
I think it is another compact implementation.

**Comment by xofbd** [comment]
I agree with xuanyuan9288. I noticed the mistake the other day. If you flip the sign, the L2 error of the simulation output and the manufactured solution is low, 1E-4. L should be equal to f*v*dx + g*v*ds. The Poisson tutorial found in the link below is consisted with L = f*v*dx + g*v*ds formulation.

https://fenics.readthedocs.io/projects/dolfin/en/latest/demos/demo_poisson.py.html

**Comment by alogg** [comment]
I think the book is correct. Integrate by parts and you get the flux q = -du/dn in the left-hand side. The flux is given by +g so when g is moved to the right-hand side you get -g.

**Comment by xuanyuan9288** [comment]
Dear alogg,
I didn't mean that the variational formulation is wrong. I only want to point out the mistake of _g_ on page 84.
In my view, 
_g = -4_
on _y = 1_.

I tried the code written in the book, and the result shows as:
error_L2  = 0.905974239064
error_max = 2.93915588563

However, if I change the code, the result shows as:
error_L2  = 0.00823509807336
error_max = 2.44249065418e-15

I paste the code here. I will be very happy if you check the code.
Thank you.

**from __future__ import print_function
from fenics import *

# Create mesh and define function space
mesh = UnitSquareMesh(8, 8)
V = FunctionSpace(mesh, 'P', 1)

# Define boundary condition
u_D = Expression('1 + x[0]*x[0] + 2*x[1]*x[1]', degree=2)

tol = 1E-14

def boundary_D(x, on_boundary):
    return on_boundary and (near(x[0], 0 ,tol) or near(x[0], 1, tol))

bc = DirichletBC(V, u_D, boundary_D)

# Define variational problem
u = TrialFunction(V)
v = TestFunction(V)
f = Constant(-6.0)
g = Expression('-4*x[1]', degree = 1)
a = dot(grad(u), grad(v))*dx
L = f*v*dx - g*v*ds

# Compute solution
u = Function(V)
solve(a == L, u, bc)

# Plot solution and mesh
plot(u)
plot(mesh)

# Save solution to file in VTK format
vtkfile = File('poisson/solution.pvd')
vtkfile << u

# Compute error in L2 norm
error_L2 = errornorm(u_D, u, 'L2')

# Compute maximum error at vertices
vertex_values_u_D = u_D.compute_vertex_values(mesh)
vertex_values_u = u.compute_vertex_values(mesh)
import numpy as np
error_max = np.max(np.abs(vertex_values_u_D - vertex_values_u))

# Print errors
print('error_L2  =', error_L2)
print('error_max =', error_max)

# Hold plot
interactive()**

**Comment by xuanyuan9288** [comment]
Dear alogg,
I didn't mean that the variational formulation is wrong. I only want to point out the mistake of _g_ on page 84.
In my view,
_g = -4_
on _y = 1_.

I tried the code written in the book, and the result shows as:
_error_L2 = 0.905974239064
error_max = 2.93915588563_

However, if I change the code, the result shows as:
_error_L2 = 0.00823509807336
error_max = 2.44249065418e-15_

I paste the code here. I will be very happy if you can check the code.
Thank you.

from __future__ import print_function
from fenics import *

# Create mesh and define function space
mesh = UnitSquareMesh(8, 8)
V = FunctionSpace(mesh, 'P', 1)

# Define boundary condition
u_D = Expression('1 + x[0]*x[0] + 2*x[1]*x[1]', degree=2)

tol = 1E-14

def boundary_D(x, on_boundary):
    return on_boundary and (near(x[0], 0 ,tol) or near(x[0], 1, tol))

bc = DirichletBC(V, u_D, boundary_D)

# Define variational problem
u = TrialFunction(V)
v = TestFunction(V)
f = Constant(-6.0)
g = Expression('-4*x[1]', degree = 1)
a = dot(grad(u), grad(v))*dx
L = f*v*dx - g*v*ds

# Compute solution
u = Function(V)
solve(a == L, u, bc)

# Plot solution and mesh
plot(u)
plot(mesh)

# Save solution to file in VTK format
vtkfile = File('poisson/solution.pvd')
vtkfile << u

# Compute error in L2 norm
error_L2 = errornorm(u_D, u, 'L2')

# Compute maximum error at vertices
vertex_values_u_D = u_D.compute_vertex_values(mesh)
vertex_values_u = u.compute_vertex_values(mesh)
import numpy as np
error_max = np.max(np.abs(vertex_values_u_D - vertex_values_u))

# Print errors
print('error_L2  =', error_L2)
print('error_max =', error_max)

# Hold plot
interactive()

**Comment by xuanyuan9288** [comment]
Dear alogg,
I didn't mean that the variational formulation is wrong. I only want to point out the mistake of _g_ on page 84.
In my view,
_g = -4_
on _y = 1_.

I tried the code written in the book, and the result shows as:
_error_L2 = 0.905974239064
error_max = 2.93915588563_

However, if I change the code, the result shows as:
_error_L2 = 0.00823509807336
error_max = 2.44249065418e-15_

I paste the code here, and I will be very happy if you can check the code.
Thank you.

[test.txt](https://github.com/hplgit/fenics-tutorial/files/759617/test.txt)

**Comment by xuanyuan9288** [comment]
Dear alogg,
I didn't mean that the variational formulation is wrong. I only want to point out the mistake of _g_ on page 84.
In my view,
_g = -4_
on _y = 1_.

I tried the code written in the book, and the result shows as:
_error_L2 = 0.905974239064
error_max = 2.93915588563_

However, if I change the code, the result shows as:
_error_L2 = 0.00823509807336
error_max = 2.44249065418e-15_

I paste the code here, and I will be very happy if you can check the code.
Thank you.

`from __future__ import print_function
from fenics import *

# Create mesh and define function space
mesh = UnitSquareMesh(8, 8)
V = FunctionSpace(mesh, 'P', 1)

# Define boundary condition
u_D = Expression('1 + x[0]*x[0] + 2*x[1]*x[1]', degree=2)

tol = 1E-14

def boundary_D(x, on_boundary):
    return on_boundary and (near(x[0], 0 ,tol) or near(x[0], 1, tol))

bc = DirichletBC(V, u_D, boundary_D)

# Define variational problem
u = TrialFunction(V)
v = TestFunction(V)
f = Constant(-6.0)
g = Expression('-4*x[1]', degree = 1)
a = dot(grad(u), grad(v))*dx
L = f*v*dx - g*v*ds

# Compute solution
u = Function(V)
solve(a == L, u, bc)

# Plot solution and mesh
plot(u)
plot(mesh)

# Save solution to file in VTK format
vtkfile = File('poisson/solution.pvd')
vtkfile << u

# Compute error in L2 norm
error_L2 = errornorm(u_D, u, 'L2')

# Compute maximum error at vertices
vertex_values_u_D = u_D.compute_vertex_values(mesh)
vertex_values_u = u.compute_vertex_values(mesh)
import numpy as np
error_max = np.max(np.abs(vertex_values_u_D - vertex_values_u))

# Print errors
print('error_L2  =', error_L2)
print('error_max =', error_max)

# Hold plot
interactive()
`

**Comment by alogg** [comment]
You mean that the formulation is correct but if

u = 1 + x2 + 2y2

then at y = 1 we have g = -du/dn = -du/dy = -4y = -4.

Yes! Now I understand.

Please make a pull request for both the text and the code example.

Thanks for spotting this.

--

Anders



ons 8 feb. 2017 kl 04:01 skrev xuanyuan9288 <notifications@github.com>:

**Comment by xuanyuan9288** [comment]
Dear alogg,
Thank you for your response on my issues. I'm afraid to say that I can't make a pull request. This is my first time to use github. Yesterday, I read the help documents about fork and pull requests, but I still confused about them. Moreover, I didn't find the files I should fix. I'm very sorry about that.
Best wishes for you.

**Comment by alogg** [comment]
Fixed now, thanks!
