### ISSUE TITLE
Paraview 4.0.1 visualization of heat equation

### ISSUE THREAD

**Issue by joha2** [hplgit/fenics-tutorial#24]
The visualization of the solution of the heat equation in Paraview 4.0.1 only works in the described manner if one loads the vtu file instead of the pvd one. Maybe this could be hinted somewhere. Best wishes Johannes

**Comment by alogg** [comment]
That sounds more like a bug in Paraview than a bug in the book...

**Comment by joha2** [comment]
OK, it was just a suggestion. In particular for the users running a more conservative Linux distribution, such a hint would be useful. Best regards, Johannes
