### ISSUE TITLE
ImportError: No module named boxfield

### ISSUE THREAD

**Issue by xuanyuan9288** [hplgit/fenics-tutorial#27]
On the page 136, the module _boxfield_ can't be imported in python. Moreover, the corresponding page https://fenicsproject.org/pub/tutorial/python/vol1/boxfield.py can't be found.

**Comment by arbolis** [comment]
You're right, though I can find boxfield.py at https://github.com/hplgit/fenics-tutorial/blob/master/src/vol1/python/boxfield.py

**Comment by alogg** [comment]
Thanks. Link to `boxfield.py` has been added on the tutorial page.
