### ISSUE TITLE
mesh data files missing

### ISSUE THREAD

**Issue by RizzerOnGitHub** [hplgit/fenics-tutorial#28]
Mesh data files for the tutorial examples are not provided, for instance navier_stokes_cylinder/cylinder.xml.gz, needed by the Reactive Flow example, ft09_reaction_system.py

**Comment by xuanyuan9288** [comment]
You can find the mesh data files if you run ft08_navier_stokes_cylinder.py

**Comment by RizzerOnGitHub** [comment]
I see it now, thanks xuanyuan9288.

Should a link or reference to it be given on the page?

**Comment by alogg** [comment]
Thanks for the comments. I have now added a note on this to the tutorial page (at the bottom): https://fenicsproject.org/tutorial/
