### ISSUE TITLE
Broken list in section 2.3.10; page 27

### ISSUE THREAD

**Issue by modkin** [hplgit/fenics-tutorial#29]
The list in section _2.3.10 Plotting the solution using ParaView_ on page 27 seams to be broken. 
Item 7 is interrupted and the numbering afterwards starts from 1 again

As far as I can tell the problem is in /src/vol1/fundamentals_poisson.do.txt in line 1035. 
https://github.com/hplgit/fenics-tutorial/blob/master/src/vol1/fundamentals_poisson.do.txt#L1035
There are newlines in the source code which cause the trouble

**Comment by alogg** [comment]
Thanks for noticing, I have fixed this now.
