### ISSUE TITLE
Mistake about magnetic permeability of copper, and strange code comment

### ISSUE THREAD

**Issue by arbolis** [hplgit/fenics-tutorial#31]
Hello,
It seems that there's a mistake at line 72 of https://github.com/hplgit/fenics-tutorial/blob/master/pub/python/vol1/ft11_magnetostatics.py 
It also seems this mistake comes from misreading a Wikipedia table (https://en.wikipedia.org/wiki/Permeability_(electromagnetism)#Values_for_some_common_materials) where one sees that -6.4 x 10 ^-6 is the value of the susceptibility of copper, not its permeability. The permeability should be 1.256629×10−6 or som which is positive, not negative as claimed.
Also at line 70 of the above file, one reads "values[0] = 1e-5 # iron (should really be 2.5e-1)"   But according to the Wikipedia table, only 99.95% pure iron should get the very high 2.5e-1 permeability. In the same table it is written that iron pure at 99.8% has a permeability of 6.3×10−3. 
So it's really not clear to me as to why "should really be 2.5e-1" is written as a comment to the code.

**Comment by alogg** [comment]
Thanks for spotting this! I had indeed looked in the wrong column... Fixed now. The value of 6.3e-3 is still too high to get a nice looking plot so I kept the iron permeability at 1e-5 (but changed the comment). Value for copper replaced with 1.26e-6.
