### ISSUE TITLE
Module 'BoxField' not in src/modules

### ISSUE THREAD

**Issue by akdiem** [hplgit/fenics-tutorial#37]
The section "Taking advantage of structured mesh data" says:

> In the directory src/modules, associated with this book, we have included the Python module BoxField that provides utilities for working with structured mesh data in FEniCS.

However, there is no directory modules in src.

**Comment by alogg** [comment]
The module can be found at the bottom of this page: https://fenicsproject.org/tutorial/

And the online version has already been updated to reflect this. Thanks for the comment.
