### ISSUE TITLE
Install FEniCS on Ubuntu 18.04

### ISSUE THREAD

**Issue by OsbertWang** [hplgit/fenics-tutorial#46]
Hello.

I install FeniCS on ubuntu 18.04 following the download webpage.
However, when I finish, and run 
python -c 'import fenics'
the system tells me no module named fenics.
Is there something wrong?

**Comment by OsbertWang** [comment]
Just use python3 instead of python.

**Comment by landauroj** [comment]
It did not work with me! : python3 -c 'import fenics' 
Anaconda3 (Spyder3) is in my home directory and fenics packages included 'Dolfin' are somewhere in my Ubuntu 19.04 machine. Fenics or dolfin are not in my home directory. Do I need to do something with PATH? How to link Anaconda3 with all the packages provided by downloading fenics?
